FROM ubuntu:21.04 as base_dependencies

ENV LD_LIBRARY_PATH=/usr/local/lib/

RUN DEBIAN_FRONTEND=noninteractive apt update -y \
 && DEBIAN_FRONTEND=noninteractive apt --no-install-recommends -y full-upgrade \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
      sudo \
      gdebi-core \
      xz-utils

FROM base_dependencies as chat_client

COPY build/ubuntu/otp-voip_1.0.2_all.deb /
RUN DEBIAN_FRONTEND=noninteractive gdebi --non-interactive otp-voip_1.0.2_all.deb

      
# sudo docker build -t otp-voip/otp-voip:amd64-ubuntu-lite-1.18.4-1.4.2-20210428 -f Dockerfile_ubuntu_lite_1.18.4 .

