FROM ubuntu:20.04 as base_dependencies

ENV LD_LIBRARY_PATH=/usr/local/lib/

RUN DEBIAN_FRONTEND=noninteractive apt update -y \
 && DEBIAN_FRONTEND=noninteractive apt --no-install-recommends -y full-upgrade \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
      sudo \
      gdebi-core \
      xz-utils

FROM base_dependencies as gstreamer_dependencies

COPY build/ubuntu/srt_1.4.2.20210428-1_amd64.deb /
COPY build/ubuntu/webrtc-audio-processing_0.3.1.20210428-1_amd64.deb /
COPY build/ubuntu/gstreamer-voip_1.18.4.20210428-1_amd64.deb /
RUN DEBIAN_FRONTEND=noninteractive gdebi --non-interactive srt_1.4.2.20210428-1_amd64.deb \
 && DEBIAN_FRONTEND=noninteractive gdebi --non-interactive webrtc-audio-processing_0.3.1.20210428-1_amd64.deb \
 && DEBIAN_FRONTEND=noninteractive gdebi --non-interactive gstreamer-voip_1.18.4.20210428-1_amd64.deb

FROM gstreamer_dependencies as chat_client

COPY build/otp-voip_1.0.0_all.deb /
RUN DEBIAN_FRONTEND=noninteractive gdebi --non-interactive otp-voip_1.0.0_all.deb


# sudo docker build -t otp-voip/otp-voip:amd64-ubuntu-1.18.4-1.4.2-20210428 -f Dockerfile_ubuntu_1.18.4 .

