FROM debian:buster as base_dependencies

ENV LD_LIBRARY_PATH=/usr/local/lib/

RUN DEBIAN_FRONTEND=noninteractive apt update -y \
 && DEBIAN_FRONTEND=noninteractive apt --no-install-recommends -y full-upgrade \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
      software-properties-common \
      wget \
      gnupg2 \
      ca-certificates
COPY ./build/etc_apt_sources.list.d_raspi.list /etc/apt/sources.list.d/raspi.list
RUN wget -qO - http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | apt-key add - \
 && DEBIAN_FRONTEND=noninteractive apt update --no-install-recommends -y --force-yes \
 && DEBIAN_FRONTEND=noninteractive apt dist-upgrade --no-install-recommends -y --force-yes \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y --force-yes \
      libraspberrypi0 \
      libraspberrypi-bin \
      libraspberrypi-dev \      
      raspberrypi-bootloader \
      raspberrypi-kernel
      
RUN DEBIAN_FRONTEND=noninteractive apt update -y \
 && DEBIAN_FRONTEND=noninteractive apt --no-install-recommends -y full-upgrade \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
      sudo \
      gdebi-core \
      xz-utils

FROM base_dependencies as gstreamer_dependencies
      
COPY build/srt_1.4.2.20210428-1_armhf.deb /
COPY build/webrtc-audio-processing_0.3.1.20210428-1_armhf.deb /
COPY build/gstreamer-voip_1.18.4.20210428-1_armhf.deb /
RUN gdebi --non-interactive srt_1.4.2.20210428-1_armhf.deb \
 && gdebi --non-interactive webrtc-audio-processing_0.3.1.20210428-1_armhf.deb \
 && gdebi --non-interactive gstreamer-voip_1.18.4.20210428-1_armhf.deb

FROM gstreamer_dependencies as chat_client

COPY build/otp-voip_1.0.0_all.deb /
RUN gdebi --non-interactive otp-voip_1.0.0_all.deb

      
# sudo docker build -t otp-voip/otp-voip:pi-1.18.4-1.4.2-20210428 -f Dockerfile_pi_1.18.4 .

