FROM debian:buster as base_dependencies

ENV LD_LIBRARY_PATH=/usr/local/lib/


RUN DEBIAN_FRONTEND=noninteractive apt update -y \
 && DEBIAN_FRONTEND=noninteractive apt --no-install-recommends -y full-upgrade \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
      software-properties-common \
      sudo \
      ca-certificates \
      expect \
      git \
      python3-pip \
      python-gi-dev \
      ninja-build \
      wget \
      gnupg2 \
 && pip3 install meson
COPY ./build/etc_apt_sources.list.d_raspi.list /etc/apt/sources.list.d/raspi.list
RUN wget -qO - http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | apt-key add - \
 && DEBIAN_FRONTEND=noninteractive apt update --no-install-recommends -y --force-yes \
 && DEBIAN_FRONTEND=noninteractive apt dist-upgrade --no-install-recommends -y --force-yes \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y --force-yes \
      libraspberrypi0 \
      libraspberrypi-bin \
      libraspberrypi-dev \      
      raspberrypi-bootloader \
      raspberrypi-kernel


FROM base_dependencies as gstreamer_dependencies

RUN DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
      libasound2-plugins \
      libpulsedsp \
      pulseaudio \
      pulseaudio-utils \
      rtkit \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y --force-yes \
      build-essential autotools-dev automake autoconf \
      libtool autopoint libxml2-dev zlib1g-dev libglib2.0-dev \
      pkg-config bison flex python3 git gtk-doc-tools libasound2-dev \
      libgudev-1.0-dev libxt-dev libvorbis-dev libcdparanoia-dev \
      libpango1.0-dev libtheora-dev libvisual-0.4-dev iso-codes \
      libgtk-3-dev libraw1394-dev libiec61883-dev libavc1394-dev \
      libv4l-dev libcairo2-dev libcaca-dev libspeex-dev libpng-dev \
      libshout3-dev libjpeg-dev libaa1-dev libflac-dev libdv4-dev \
      libtag1-dev libwavpack-dev libpulse-dev libsoup2.4-dev libbz2-dev \
      libcdaudio-dev libdc1394-22-dev ladspa-sdk libass-dev \
      libcurl4-gnutls-dev libdca-dev libdvdnav-dev \
      libexempi-dev libexif-dev libfaad-dev libgme-dev libgsm1-dev \
      libiptcdata0-dev libkate-dev libmimic-dev libmms-dev \
      libmodplug-dev libmpcdec-dev libofa0-dev libopus-dev \
      librsvg2-dev librtmp-dev \
#      libschroedinger-dev libslv2-dev \
      libsndfile1-dev libsoundtouch-dev libspandsp-dev libx11-dev \
      libxvidcore-dev libzbar-dev libzvbi-dev liba52-0.7.4-dev \
      libcdio-dev libdvdread-dev libmad0-dev libmp3lame-dev \
      libmpeg2-4-dev libopencore-amrnb-dev libopencore-amrwb-dev \
      libsidplay1-dev libtwolame-dev libx264-dev libusb-1.0 \
      python-gi-dev yasm python3-dev libgirepository1.0-dev gettext \
      libxv-dev libnice-dev tclsh cmake libssl-dev \
      libva-dev
RUN mkdir /build \
 && cd /build \
 && git clone https://github.com/giuliomoro/checkinstall \
 && cd checkinstall \
 && make install
RUN cd /build \
 && git clone https://github.com/Haivision/srt \
 && cd srt \
 && git checkout v1.4.2 \
# && git checkout master \
 && ./configure --prefix=/usr/ \
 && make CFLAGS="-Wno-error" -j4 \
 && checkinstall -D --install=yes --fstrans=no --pkgname=srt --provides=srt --pkgversion=1.4.2.20210428 --nodoc -y
RUN cd /build \
 && git clone git://anongit.freedesktop.org/pulseaudio/webrtc-audio-processing \
 && cd webrtc-audio-processing \
 && git checkout v0.3.1 \
 && ./autogen.sh \
 && make CFLAGS="-Wno-error" -j4 \
 && checkinstall -D --install=yes --fstrans=no --pkgname=webrtc-audio-processing --provides=webrtc-audio-processing --pkgversion=0.3.1.20210428 --nodoc -y
RUN cd /build \
 && mkdir gstreamer-src \
 && cd gstreamer-src \
 && git clone https://github.com/GStreamer/gst-build
RUN cd /build/gstreamer-src/gst-build \
 && git checkout 1.18.4 \
 && meson builddir \
 && ninja -C builddir
# hack to reduce DEFAULT_LATENCY for mpegtsmux
RUN cd /build/gstreamer-src/gst-build \
 && sed -i 's/DEFAULT_LATENCY (700)/DEFAULT_LATENCY (100)/g' /build/gstreamer-src/gst-build/gst-plugins-bad/gst/mpegtsdemux/tsdemux.c \
 && ninja -C builddir
RUN cd /build/gstreamer-src/gst-build \
 && ninja -C builddir \
# && meson install -C builddir
 && sudo checkinstall -D \
     --install=yes \
     --fstrans=no \
     --pkgname=gstreamer-voip \
     --provides=gstreamer-voip \
     --pkgversion=1.18.4.20210428 \
     --nodoc \
     --default \
     --provides= \
     --requires="srt \(\>=1.4.2.20210428-1\),\
                 webrtc-audio-processing \(\>=0.3.1.20210428-1\),\
                 libasound2-plugins, \
                 libpulsedsp, \
                 pulseaudio, \
                 pulseaudio-utils, \
                 rtkit, \
                 libpython3.7, \
                 libilmbase23, \
                 libopenexr-dev, \
                 libcurl3-gnutls, \
                 libxml2, zlib1g, libglib2.0-0, libglib2.0-bin, libglib2.0-data, \
                 pkg-config, bison, flex, python3, gtk-doc-tools, libasound2, \
                 libgudev-1.0-0, libxt6, libvorbis0a, libvorbisenc2, libvorbisfile3, libcdparanoia0, \
                 libpango1.0-dev, libtheora0, libvisual-0.4-0, iso-codes, \
                 libgtk-3-0, libgtk-3-common, libgtk-3-dev, libraw1394-11, libiec61883-0, libavc1394-0, \
                 libv4l-0, libv4l2rds0, libv4lconvert0, libcairo2, libcaca0, libspeex1, libspeexdsp1, libpng16-16, \
                 libshout3, libjpeg62-turbo, libaa1, libflac8, libdv4, \
                 libtag1v5, libtag1v5-vanilla, libwavpack1, libpulse0, libpulsedsp, libpulse-mainloop-glib0, libsoup2.4-1, libbz2-1.0, \
                 libcdaudio1, libdc1394-22, ladspa-sdk, libass9, \
                 libcurl4, libdca0, libdvdnav4, \
                 libexempi8, libexif12, libfaad2, libgme0, libgsm1, \
                 libiptcdata0, libkate1, libmimic0, libmms0, \
                 libmodplug1, libmpcdec6, libofa0, libopus0, \
                 librsvg2-2, librsvg2-common, librtmp1, \
                 libsndfile1, libsoundtouch1, libspandsp2, libx11-6, libx11-data, libx11-xcb1, \
                 libxvidcore4, libzbar0, libzvbi0, libzvbi-common, liba52-0.7.4, \
                 libcdio18, libdvdread4, libmad0, libmp3lame0, \
                 libmpeg2-4, libopencore-amrnb0, libopencore-amrwb0, \
                 libsidplay1v5, libtwolame0, libx264-155, libusb-1.0-0, \
                 python-gi, yasm, libgirepository-1.0-1, gettext, \
                 libxv1, libnice10, tclsh, libssl1.1, \
                 libva2, libva-drm2, libva-glx2, libva-wayland2, libva-x11-2 \
                " \
     --conflicts="gstreamer1.0-alsa, \
                  gstreamer1.0-gl, \
                  gstreamer1.0-libav, \
                  gstreamer1.0-nice, \
                  gstreamer1.0-plugins-bad, \
                  gstreamer1.0-plugins-base, \
                  gstreamer1.0-plugins-good, \
                  gstreamer1.0-plugins-ugly, \
                  gstreamer1.0-plugins-rtp, \
                  gstreamer1.0-pulseaudio, \
                  gstreamer1.0-python3-plugin-loader, \
                  gstreamer1.0-rtsp, \
                  gstreamer1.0-tools, \
                  gstreamer1.0-vaapi, \
                  gstreamer1.0-x \
                 " \
     meson install -C builddir

FROM gstreamer_dependencies as chat_client

RUN DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
      python-pip \
      python3-pip \
      python3-tk \
      python3-setuptools \
#      python3-rpi.gpio \
      libatlas-base-dev \
      v4l-utils
RUN pip3 install \
      numpy \
      pulsectl
            

      
# sudo docker build -t otp-voip/otp-voip-build:pi-1.18.4-1.4.2-20210428 -f Dockerfile_pi_build_1.18.4 .
# x11docker -- --volume $HOME/Docker/otp-voip/build:$HOME/build --rm -- otp-voip/otp-voip-build:pi-1.18.4-1.4.2-20210428 /bin/bash -c "cp /build/srt/*.deb ~/build/; cp /build/webrtc-audio-processing/*.deb ~/build/; cp /build/gstreamer-src/gst-build/*.deb ~/build"

